f = open('encryptedWithPublic.txt', 'rb')
fd = open('d.txt','r')
fn = open('n.txt','r')
n = int(fn.read())
d = int(fd.read())
binary = f.read()
message = int.from_bytes(binary,"big")
P = pow(message, d, n)
back_to_binary = P.to_bytes((P.bit_length() + 7)// 8, "big")
f2 = open('encryptedWithPrivate.txt', 'wb')
f2.write(back_to_binary)
f2.close()
