f = open('message.txt', 'rb')
fe = open('e.txt','r')
fn = open('n.txt','r')
n = int(fn.read())
e = int(fe.read())
binary = f.read()
message = int.from_bytes(binary,"big")
P = pow(message, e, n)
back_to_binary = P.to_bytes((P.bit_length() + 7)// 8, "big")
f2 = open('encryptedWithPublic.txt', 'wb')
f2.write(back_to_binary)
f2.close()
